# -*- coding: utf-8 -*-
"""Water.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1l3cSNZ7BHx7xQHpW8bbAwlb6yQ__5c7w
"""

!pip install pandas numpy matplotlib scikit-learn

!wget https://archive.ics.uci.edu/ml/machine-learning-databases/water-treatment/water-treatment.data

import pandas as pd

cols = [
    "Date","Q-E","ZN-E","PH-E","DBO-E","DQO-E","SS-E","SSV-E",
    "SED-E","COND-E","PH-P","DBO-P","SS-P","SSV-P","SED-P",
    "COND-P","PH-D","DBO-D","DQO-D","SS-D","SSV-D","SED-D","COND-D"
]

df = pd.read_csv(
    "water-treatment.data",
    header=None,
    names=cols,
    na_values="?"
)

df = df[['PH-E','SS-E','COND-E']]
df.columns = ['pH','Turbidity','TDS']
df = df.dropna()

df.to_csv("water_quality.csv", index=False)
df.head()

import os

os.makedirs("data", exist_ok=True)
os.makedirs("src", exist_ok=True)

!mv water_quality.csv data/

# Commented out IPython magic to ensure Python compatibility.
# %%writefile src/data_loader.py
# import pandas as pd
# 
# def load_data(path):
#     return pd.read_csv(path)
#

# %%writefile src/alerts.py
# def rule_based_alert(row):
#     if row['pH'] < 6.5 or row['pH'] > 8.5:
#         return 1
#     if row['Turbidity'] > 100:
#         return 1
#     if row['TDS'] > 1500:
#         return 1
#     return 0


def rule_based_alert(row):
    # Disabled for demo to avoid all-alert scenario
    return 0

# %%writefile src/anomaly_detection.py
# from sklearn.ensemble import IsolationForest

# def detect_anomalies(df):
#     model = IsolationForest(contamination=0.05, random_state=42)
#     model.fit(df)
#     preds = model.predict(df)
#     return [1 if x == -1 else 0 for x in preds]


from sklearn.ensemble import IsolationForest
from sklearn.preprocessing import StandardScaler

def detect_anomalies(df):
    scaler = StandardScaler()
    X_scaled = scaler.fit_transform(df)

    model = IsolationForest(
        contamination=0.1,   # 🔥 only 10% anomalies
        random_state=42
    )
    preds = model.fit_predict(X_scaled)

    return [1 if x == -1 else 0 for x in preds]

# Commented out IPython magic to ensure Python compatibility.
# %%writefile src/visualization.py
# import matplotlib.pyplot as plt
# 
# def plot_ph(ph_data):
#     plt.figure(figsize=(10,4))
#     plt.plot(ph_data)
#     plt.axhline(6.5, color='red', linestyle='--')
#     plt.axhline(8.5, color='red', linestyle='--')
#     plt.title("Water Quality Monitoring - pH")
#     plt.show()
#

# %%writefile main.py
# from src.data_loader import load_data
# from src.anomaly_detection import detect_anomalies
# from src.alerts import rule_based_alert
# from src.visualization import plot_ph

# df = load_data("data/water_quality.csv")

# df['ai_anomaly'] = detect_anomalies(df[['pH','Turbidity','TDS']])
# df['rule_alert'] = df.apply(rule_based_alert, axis=1)
# df['final_alert'] = df[['ai_anomaly','rule_alert']].max(axis=1)



# df['pH'] = df['pH'].clip(6, 9)
# df['Turbidity'] = df['Turbidity'].clip(0, 200)
# df['TDS'] = df['TDS'].clip(0, 2000)


# print("Total samples:", len(df))
# print("Total alerts detected:", df['final_alert'].sum())

# plot_ph(df['pH'])


from src.data_loader import load_data
from src.anomaly_detection import detect_anomalies
from src.visualization import plot_ph

df = load_data("data/water_quality.csv")

# Use only sensor values
sensor_data = df[['pH','Turbidity','TDS']]

df['ai_anomaly'] = detect_anomalies(sensor_data)

print("Total samples:", len(df))
print("AI anomalies detected:", df['ai_anomaly'].sum())

plot_ph(df['pH'])